drwxr-xr-x@    - macbookair 11 Jan 17:37 -N .
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I ├── build
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── WeeklyWinner
.rw-r--r--@ 1.3k macbookair 11 Jan 01:21 -I │   └── WeeklyWinner.compiled.json
drwxr-xr-x@    - macbookair 11 Jan 01:21 -- ├── contracts
.rw-r--r--@  592 macbookair 11 Jan 01:21 -- │   └── weekly_winner.tact
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I ├── node_modules
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @ampproject
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @assemblyscript
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @babel
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @bcoe
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @cspotcode
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @ipld
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @istanbuljs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @jridgewell
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @multiformats
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @protobufjs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @sinclair
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @sinonjs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @tact-lang
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @ton
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @ton-api
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @ton-community
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @tonconnect
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @tsconfig
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── @types
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── acorn
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── acorn-walk
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ansi-escapes
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ansi-regex
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ansi-styles
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── anymatch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── arg
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── argparse
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── async
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── asynckit
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── axios
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── babel-jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── babel-plugin-istanbul
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── babel-plugin-jest-hoist
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── babel-preset-current-node-syntax
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── babel-preset-jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── balanced-match
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── base64-js
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── bignumber.js
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── bl
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── blockstore-core
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── brace-expansion
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── braces
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── browserslist
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── bs-logger
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── bser
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── buffer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── buffer-from
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── callsites
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── camel-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── camelcase
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── caniuse-lite
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── capital-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── chalk
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── change-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── char-regex
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── chardet
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ci-info
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cjs-module-lexer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cli-cursor
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cli-spinners
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cli-width
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cliui
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── clone
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── co
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── collect-v8-coverage
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── color-convert
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── color-name
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── combined-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── concat-map
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── constant-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── convert-source-map
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── core-js-pure
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── crc-32
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── create-jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── create-require
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── cross-spawn
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── dataloader
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── debug
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── dedent
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── deepmerge
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── defaults
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── delayed-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── detect-newline
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── diff
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── diff-sequences
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── dot-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── dotenv
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ejs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── electron-to-chromium
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── emittery
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── emoji-regex
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── err-code
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── error-ex
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── escalade
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── escape-string-regexp
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── esprima
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── eventsource
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── execa
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── exit
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── expect
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── external-editor
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── fast-json-stable-stringify
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── fb-watchman
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── figures
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── filelist
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── fill-range
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── find-up
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── follow-redirects
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── form-data
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── fs.realpath
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── fsevents
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── function-bind
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── gensync
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── get-caller-file
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── get-package-type
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── get-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── glob
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── globals
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── graceful-fs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── hamt-sharding
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── has-flag
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── hasown
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── header-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── html-escaper
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── human-signals
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── iconv-lite
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ieee754
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── import-local
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── imurmurhash
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── inflight
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── inherits
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── inquirer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── interface-blockstore
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── interface-store
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ipfs-unixfs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ipfs-unixfs-importer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-arrayish
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-core-module
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-fullwidth-code-point
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-generator-fn
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-interactive
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-number
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-plain-obj
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── is-unicode-supported
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── isexe
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── istanbul-lib-coverage
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── istanbul-lib-instrument
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── istanbul-lib-report
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── istanbul-lib-source-maps
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── istanbul-reports
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-all
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-batch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-drain
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-filter
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-first
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-parallel-batch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── it-take
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jake
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-changed-files
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-circus
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-cli
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-config
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-diff
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-docblock
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-each
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-environment-node
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-get-type
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-haste-map
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-leak-detector
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-matcher-utils
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-message-util
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-mock
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-pnp-resolver
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-regex-util
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-resolve
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-resolve-dependencies
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-runner
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-runtime
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-snapshot
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-util
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-validate
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-watcher
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jest-worker
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── js-tokens
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── js-yaml
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jsesc
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── json-bigint
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── json-parse-even-better-errors
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── json5
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── jssha
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── kleur
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── leven
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── lines-and-columns
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── locate-path
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── lodash
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── lodash.memoize
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── log-symbols
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── long
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── lower-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── lru-cache
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── make-dir
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── make-error
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── makeerror
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── meow
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── merge-options
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── merge-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── micromatch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── mime-db
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── mime-types
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── mimic-fn
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── minimatch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── minimist
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── mkdirp
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ms
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── multiformats
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── murmurhash3js-revisited
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── mute-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── natural-compare
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── no-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── node-fetch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── node-inspect-extracted
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── node-int64
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── node-releases
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── normalize-path
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── npm-run-path
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ohm-js
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── once
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── onetime
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ora
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── os-tmpdir
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── p-limit
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── p-locate
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── p-try
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── param-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── parse-json
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── pascal-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-exists
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-is-absolute
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-key
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-normalize
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── path-parse
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── picocolors
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── picomatch
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── pirates
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── pkg-dir
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── prando
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── prettier
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── pretty-format
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── prompts
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── protobufjs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── proxy-from-env
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── pure-rand
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── qrcode-terminal
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── rabin-wasm
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── react-is
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── readable-stream
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── require-directory
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── resolve
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── resolve-cwd
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── resolve-from
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── resolve.exports
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── restore-cursor
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── run-async
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── rxjs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── safe-buffer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── safer-buffer
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── semver
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── sentence-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── shebang-command
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── shebang-regex
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── signal-exit
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── sisteransi
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── slash
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── snake-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── source-map
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── source-map-support
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── sparse-array
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── sprintf-js
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── stack-utils
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── string-length
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── string-width
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── string_decoder
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── strip-ansi
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── strip-bom
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── strip-final-newline
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── strip-json-comments
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── supports-color
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── supports-preserve-symlinks-flag
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── symbol.inspect
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── teslabot
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── test-exclude
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── through
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tmp
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tmpl
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── to-regex-range
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tr46
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ts-jest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── ts-node
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tslib
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tweetnacl
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── tweetnacl-util
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── type-detect
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── type-fest
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── typescript
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── uint8arrays
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── undici-types
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── update-browserslist-db
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── upper-case
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── upper-case-first
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── util-deprecate
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── v8-compile-cache-lib
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── v8-to-istanbul
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── walker
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── wcwidth
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── webidl-conversions
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── whatwg-url
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── which
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── wrap-ansi
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── wrappy
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── write-file-atomic
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── y18n
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── yallist
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── yargs
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── yargs-parser
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── yn
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   ├── yocto-queue
drwxr-xr-x@    - macbookair 11 Jan 01:21 -I │   └── zod
drwxr-xr-x@    - macbookair 11 Jan 01:21 -- ├── scripts
.rw-r--r--@  617 macbookair 11 Jan 01:21 -- │   ├── deployWeeklyWinner.ts
.rw-r--r--@ 1.3k macbookair 11 Jan 01:21 -- │   └── incrementWeeklyWinner.ts
drwxr-xr-x@    - macbookair 11 Jan 01:21 -- ├── tests
.rw-r--r--@ 2.5k macbookair 11 Jan 01:21 -- │   └── WeeklyWinner.spec.ts
drwxr-xr-x@    - macbookair 11 Jan 01:21 -- ├── wrappers
.rw-r--r--@  199 macbookair 11 Jan 01:21 -- │   ├── WeeklyWinner.compile.ts
.rw-r--r--@   57 macbookair 11 Jan 01:21 -- │   └── WeeklyWinner.ts
.rw-r--r--@  199 macbookair 11 Jan 01:20 -- ├── jest.config.ts
.rw-r--r--@  884 macbookair 11 Jan 17:37 -N ├── l1.sh
.rw-r--r--@    0 macbookair 11 Jan 17:37 -N ├── l2.sh
.rw-r--r--@ 241k macbookair 11 Jan 01:21 -- ├── package-lock.json
.rw-r--r--@  634 macbookair 11 Jan 01:20 -- ├── package.json
.rw-r--r--@  726 macbookair 11 Jan 01:20 -- ├── README.md
.rw-r--r--@ 1.1M macbookair 11 Jan 17:36 -N ├── tree.sh
.rw-r--r--@  284 macbookair 11 Jan 01:20 -- └── tsconfig.json
